name: module3_task0
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Runs once per day

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Validate Makefile
      run: make help
