name: module3_task0

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Go and Hugo
        run: |
          sudo apt-get update
          sudo apt-get install golang -y
          curl -LO https://github.com/gohugoio/hugo/releases/latest/download/hugo_extended_0.88.1_Linux-64bit.tar.gz
          tar -xf hugo_extended_0.88.1_Linux-64bit.tar.gz
          sudo mv hugo /usr/local/bin/
          go version
          hugo version

      - name: Build
        run: |
          make build
